// <auto-generated />
using System;
using EnglishVocabularyMemorization;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EnglishVocabularyMemorization.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20230923112857_exam-entity")]
    partial class examentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EnglishVocabularyMemorization.Entities.Config", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("varchar(95)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Configs");
                });

            modelBuilder.Entity("EnglishVocabularyMemorization.Entities.Exam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsFinished")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastExam")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("EnglishVocabularyMemorization.Entities.Sentence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("LastAnswers")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OriginalSentence")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(190)
                        .HasColumnType("varchar(190)");

                    b.Property<Guid>("WordId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("Text")
                        .IsUnique();

                    b.HasIndex("WordId");

                    b.ToTable("Sentences");
                });

            modelBuilder.Entity("EnglishVocabularyMemorization.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Pin")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EnglishVocabularyMemorization.Entities.Word", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("LastExam")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("LastTimeReviewed")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TimesReviewed")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("WordUpId")
                        .IsRequired()
                        .HasColumnType("varchar(95)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("WordUpId")
                        .IsUnique();

                    b.ToTable("Words");
                });

            modelBuilder.Entity("ExamSentence", b =>
                {
                    b.Property<Guid>("ExamsId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("SentencesId")
                        .HasColumnType("char(36)");

                    b.HasKey("ExamsId", "SentencesId");

                    b.HasIndex("SentencesId");

                    b.ToTable("ExamSentence");
                });

            modelBuilder.Entity("EnglishVocabularyMemorization.Entities.Sentence", b =>
                {
                    b.HasOne("EnglishVocabularyMemorization.Entities.Word", "Word")
                        .WithMany("SavedSentences")
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Word");
                });

            modelBuilder.Entity("EnglishVocabularyMemorization.Entities.Word", b =>
                {
                    b.HasOne("EnglishVocabularyMemorization.Entities.User", "User")
                        .WithMany("Words")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ExamSentence", b =>
                {
                    b.HasOne("EnglishVocabularyMemorization.Entities.Exam", null)
                        .WithMany()
                        .HasForeignKey("ExamsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnglishVocabularyMemorization.Entities.Sentence", null)
                        .WithMany()
                        .HasForeignKey("SentencesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EnglishVocabularyMemorization.Entities.User", b =>
                {
                    b.Navigation("Words");
                });

            modelBuilder.Entity("EnglishVocabularyMemorization.Entities.Word", b =>
                {
                    b.Navigation("SavedSentences");
                });
#pragma warning restore 612, 618
        }
    }
}
